name: Android CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'JetpackDemo'
        required: true
        default: '1.0'
jobs:
  build:
    name: Generate App Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: D
        run: chmod +x gradlew
      - name: Bundle 'release' with Gradle
        run: ./gradlew assembleRelease
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - run: echo "Build status report=${{ job.status }}."
      - name: Upload App Apk
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}
          run: echo "fpath=${{steps.sign_apk.outputs.signedReleaseFile}} >> $GITHUB_ENV"

  release:
    name: Release App
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download apk from build
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release_apksddsdd
          release_name: release_1sdsds
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: env.fpath
          asset_name: ${{ github.event.repository.name }}.apk
          asset_content_type: application/zip
      - run: echo "Upload returned with status=${{ job.status }}."
