name: Android CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'JetpackDemo'
        required: true
        default: '1.0'
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: set up JDK
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: 17
        - name: Generate Release APK
          run: ./gradlew assembleRelease
        - name: Sign APK
          # ID used to access action output
          id: sign_app
          uses: r0adkll/sign-android-release@v1
          with:
            releaseDirectory: app/build/outputs/bundle/release
            signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
            alias: ${{ secrets.ANDROID_KEY_ALIAS }}
            keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
            keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        - uses: actions/upload-artifact@v3
          with:
            name: release.apk
            path: ${{steps.sign_app.outputs.signedFile}}
        - uses: actions/upload-artifact@v3
          with:
            name: mapping.txt
            path: app/build/outputs/mapping/release/mapping.txt
